### ISSUE TITLE
issue with splitting the rfs likelihood into cardinality and support

### ISSUE THREAD

**Issue by eivinasbutkus** [CNCLgithub/GenRFS#11]
So I was wondering what would be a neat way to implement some distractor rendering to the mask level, as we discussed in our last meeting. The idea I came up with is to have this kind of RFS structure:

```
1. PPP (unrendered distractors)
2. MBRFS (rendered distractors)
3. MBRFS (rendered targets)
```

This kind of RFS structure would allow to immediately index the targets by just going to the last component and taking all of the observations assigned there. But I immediately stumbled into a problem of defining both the cardinality and the support for an MBRFS. While the cardinality and support separation works for Bernoulli and PPP components (given that the PPP factorial issue is adressed), I don't see how that applies in the case of MBRFS. You can get likelihood of the cardinality under the MBRFS by going through all combinations of how that cardinality could have been sampled (like all the existence probabilities). But it's unclear what the support would be in this case and whether it'd be appropriate to just multiply cardinality and support.

Possibly GenRFS should have a more general solution for likelihood calculation. I'm sure there is a way to combine the idea of a support table with a more general mechanism for likelihood without multiplying cardinality with support.

**Comment by belledon** [comment]
hey @eivinasbutkus , just wanted to let you know that there was an update on this front. 

In MOT, we noticed that the pdf of an RFS was changing as a function of cardinality alone, even when the rfs was a good explanation of the observation. That finally made this thread click for me. A RFS that is a _good_ explanation of  a large observation should have a similar log score to an RFS that is a good explanation of a small observation.

You were spot on that the discrepancy in logscore would be due to using the standard poisson pdf.
however the formula above is not the proper normalization. 
According to https://youtu.be/sRnVZVdKXLA?t=397 there is a lambda raised to the `mk` power that needs to be removed. rahter than using Gen's full logpdf and dividing by that factor, i chose to just compute the proper logpdf directly (and understanding a cool trick with `loggamma`. see ccaf785691372d657801f425313c30565323b4a9

**Comment by belledon** [comment]
just to add some closure to this. 

the current implementation is defined only for rfs where cardinality is independent of support. IE the support over observations doesnt change as a function of the sampled cardinality. 

that being said, it would be rather trivial to include as the number of observations is sampled / considered prior to drawing from support 

https://github.com/CNCLgithub/GenRFS/blob/4654f2ec4993e32cf2326b3b11877c54d8b25a46/src/rfs.jl#L27-L43

we could extend `associations` (which is in charge of computing the partition conditionals) to amortized another cardinality table if needed

https://github.com/CNCLgithub/GenRFS/blob/4654f2ec4993e32cf2326b3b11877c54d8b25a46/src/rfs.jl#L99-L125
